version: "3.9"

services:
  ros2:
    build: .
    container_name: ros2_container
    stdin_open: true
    tty: true
    network_mode: host

    volumes:
      - ./ros2_ws:/ros2_ws

    environment:
      - ROS_DOMAIN_ID=0
